services:
  app:
    image: sj0320/trippia-app:latest
    container_name: trp-app
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - redis
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
    networks:
      - backend_network
    restart: always

  mariadb:
    image: mariadb:latest
    container_name: trp-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${SPRING_DATASOURCE_USERNAME}
      MARIADB_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - backend_network
    volumes:
      - trp_mariadb_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: trp-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend_network
    volumes:
      - trp_redis_data:/data

networks:
  backend_network:
    driver: bridge

volumes:
  trp_mariadb_data:
  trp_redis_data: