spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 30

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: false

  sql:
    init:
      mode: never

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://trippia.site/login/oauth2/code/google
          naver:
            redirect-uri: https://trippia.site/login/oauth2/code/naver
          kakao:
            redirect-uri: https://trippia.site/login/oauth2/code/kakao

logging:
  file:
    name: /logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"